import { type AbilityCastRejectedPayload, type AbilityId, type AbilityOfferPayload, type AbilitySlot as AbilitySlotValue, type MatchState, type PlayerNetState, type StatKey } from "@tankes/shared";
export interface HudAudioState {
    muted: boolean;
    volume: number;
}
interface StatsHudAudioOptions {
    initialState: HudAudioState;
    onToggleMute: () => void;
    onVolumeChange: (volume: number) => void;
}
export declare class StatsHud {
    readonly element: HTMLDivElement;
    private roundPanel;
    private statsPanel;
    private playerPanel;
    private abilitiesPanel;
    private menuButton;
    private pauseMenuBackdrop;
    private pauseMenuPanel;
    private pauseMenuTabs;
    private readonly pauseMenuSections;
    private readonly pauseMenuTabButtons;
    private abilityOfferPanel;
    private abilityOfferTitle;
    private abilityOfferList;
    private abilityRejectToast;
    private tooltipPanel;
    private pendingAbilityOffer;
    private abilityRejectHideAtMs;
    private phaseText;
    private objectiveText;
    private timerText;
    private pingText;
    private scoreboardList;
    private levelText;
    private pointsText;
    private upgradeLegendText;
    private playerNameText;
    private playerMetaText;
    private playerHintText;
    private xpLabelText;
    private buffsText;
    private xpBarFill;
    private scoreboardText;
    private resultOverlay;
    private respawnOverlay;
    private muteButton;
    private volumeInput;
    private pauseMenuOpen;
    private activePauseTab;
    private lastXp;
    private lastScore;
    private currentSelfPlayer;
    private readonly rows;
    private readonly abilitySlotText;
    setAbilityOffer: (offer: AbilityOfferPayload | null) => void;
    showAbilityCastRejected(payload: AbilityCastRejectedPayload): void;
    private wireUpgradeInteraction;
    private applyDisabledStyle;
    private replayAnimationClass;
    private setPauseTab;
    private showTooltip;
    private hideTooltip;
    private bindTooltip;
    togglePauseMenu(force?: boolean): void;
    constructor(onUpgrade: (stat: StatKey) => void, onChooseAbility: (payload: {
        slot: AbilitySlotValue;
        abilityId: AbilityId;
    }) => void, audioOptions: StatsHudAudioOptions);
    dispose(): void;
    private initRoundPanel;
    private initStatsPanel;
    private initPlayerPanel;
    private initAbilitiesPanel;
    private initPauseMenu;
    private initAbilityOfferPanel;
    private initOverlays;
    setAudioState(state: HudAudioState): void;
    private renderCooldownBar;
    private renderBuffs;
    private renderTopScores;
    private buildRoundObjective;
    private updateTimer;
    private updateResultOverlay;
    private updateRespawnOverlay;
    update(selfPlayer: PlayerNetState | undefined, session: MatchState | null, serverTime: number, selfId: string | null, pingMs?: number | null): void;
}
export {};
