import { type AbilityCastRejectedPayload, type AbilityId, type AbilityOfferPayload, type AbilitySlot as AbilitySlotValue, type MatchState, type PlayerNetState, type StatKey } from "@tankes/shared";
export interface HudAudioState {
    muted: boolean;
    volume: number;
}
interface StatsHudAudioOptions {
    initialState: HudAudioState;
    onToggleMute: () => void;
    onVolumeChange: (volume: number) => void;
}
export declare class StatsHud {
    readonly element: HTMLDivElement;
    private readonly roundPanel;
    private readonly statsPanel;
    private readonly playerPanel;
    private readonly abilitiesPanel;
    private readonly menuButton;
    private readonly pauseMenuBackdrop;
    private readonly pauseMenuPanel;
    private readonly pauseMenuTabs;
    private readonly pauseMenuSections;
    private readonly pauseMenuTabButtons;
    private readonly abilityOfferPanel;
    private readonly abilityOfferTitle;
    private readonly abilityOfferList;
    private readonly abilityRejectToast;
    private readonly tooltipPanel;
    private pendingAbilityOffer;
    private abilityRejectHideAtMs;
    private readonly phaseText;
    private readonly objectiveText;
    private readonly timerText;
    private readonly pingText;
    private readonly scoreboardList;
    private readonly levelText;
    private readonly pointsText;
    private readonly upgradeLegendText;
    private readonly playerNameText;
    private readonly playerMetaText;
    private readonly playerHintText;
    private readonly xpLabelText;
    private readonly buffsText;
    private readonly xpBarFill;
    private readonly scoreboardText;
    private readonly resultOverlay;
    private readonly respawnOverlay;
    private readonly muteButton;
    private readonly volumeInput;
    private pauseMenuOpen;
    private activePauseTab;
    private lastXp;
    private lastScore;
    private currentSelfPlayer;
    private readonly rows;
    private readonly abilitySlotText;
    setAbilityOffer: (offer: AbilityOfferPayload | null) => void;
    showAbilityCastRejected(payload: AbilityCastRejectedPayload): void;
    private wireUpgradeInteraction;
    private applyDisabledStyle;
    private replayAnimationClass;
    private setPauseTab;
    private showTooltip;
    private hideTooltip;
    private bindTooltip;
    togglePauseMenu(force?: boolean): void;
    constructor(onUpgrade: (stat: StatKey) => void, onChooseAbility: (payload: {
        slot: AbilitySlotValue;
        abilityId: AbilityId;
    }) => void, audioOptions: StatsHudAudioOptions);
    setAudioState(state: HudAudioState): void;
    private renderCooldownBar;
    private renderBuffs;
    private renderTopScores;
    private buildRoundObjective;
    private updateTimer;
    private updateResultOverlay;
    private updateRespawnOverlay;
    update(selfPlayer: PlayerNetState | undefined, session: MatchState | null, serverTime: number, selfId: string | null, pingMs?: number | null): void;
}
export {};
