import { type PlayerNetState } from "@tankes/shared";
import type { InterpolatedWorld } from "./InterpolationBuffer";
export declare class CanvasRenderer {
    private readonly canvas;
    private static readonly MAX_MUZZLE_FLASHES;
    private static readonly MAX_PARTICLES;
    private static readonly MAX_TRAILS;
    private static readonly MAX_RESPAWN_PULSES;
    private static readonly MAX_DASH_EFFECTS;
    private static readonly MAX_EMP_EFFECTS;
    private static readonly MAX_BURST_EFFECTS;
    private static readonly MAX_MINE_EFFECTS;
    private static readonly MAX_TURRET_PULSES;
    private static readonly MAX_REPAIR_EFFECTS;
    private static readonly MAX_FOG_EFFECTS;
    private static readonly MAX_ORBITAL_EFFECTS;
    private static readonly MAX_HOMING_TRAILS;
    private static readonly MAX_HOMING_IMPACTS;
    private readonly context;
    private width;
    private height;
    private readonly muzzleFlashes;
    private readonly particles;
    private readonly bulletTrails;
    private readonly respawnPulses;
    private readonly dashEffects;
    private readonly empEffects;
    private readonly burstEffects;
    private readonly mineEffects;
    private readonly mineNodes;
    private readonly turretPulseEffects;
    private readonly repairEffects;
    private readonly fogEffects;
    private readonly fogZones;
    private readonly orbitalEffects;
    private readonly homingTrailEffects;
    private readonly homingImpactEffects;
    private readonly shieldAuras;
    private readonly turretNodes;
    private readonly overheatAuras;
    private readonly siegeAuras;
    private readonly seenAbilityCueExpiryById;
    private readonly previousBulletPositions;
    private selfDamageRingLife;
    private selfKillFlashLife;
    private roundTransitionLife;
    private roundTransitionLabel;
    private lastFrameTime;
    constructor(canvas: HTMLCanvasElement);
    resize(): void;
    getCameraCenter(selfPlayer: PlayerNetState | undefined): {
        x: number;
        y: number;
    };
    render(world: InterpolatedWorld, selfId: string | null): void;
    private ingestAbilityVfxCues;
    triggerShotEffect(x: number, y: number, rotation: number): void;
    triggerHitEffect(x: number, y: number, selfHit: boolean): void;
    triggerDeathEffect(x: number, y: number, selfDeath: boolean): void;
    triggerRespawnEffect(x: number, y: number): void;
    triggerKillFlash(): void;
    triggerRoundTransition(kind: "ended" | "reset"): void;
    screenToWorld(screenX: number, screenY: number, world: InterpolatedWorld, selfId: string | null): {
        x: number;
        y: number;
    };
    private drawGrid;
    private drawWorldBounds;
    private drawShapes;
    private drawControlZones;
    private drawZoneGuide;
    private drawPowerUps;
    private getPowerUpPalette;
    private getShapePalette;
    private pathRegularPolygon;
    private captureBulletTrails;
    private drawBulletTrails;
    private drawParticles;
    private drawRespawnPulses;
    private drawDashEffects;
    private drawEmpEffects;
    private drawRepairEffects;
    private drawFogEffects;
    private drawOrbitalEffects;
    private drawBurstEffects;
    private drawMineEffects;
    private drawTurretNodes;
    private drawTurretPulseEffects;
    private drawShieldAura;
    private drawOverheatAura;
    private drawSiegeAura;
    private drawHomingTrailEffects;
    private drawHomingImpactEffects;
    private drawMuzzleFlashes;
    private drawScreenEffects;
    private stepEffects;
    private pruneByLife;
    private trim;
    private hexToRgba;
}
